version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: exambyte-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: exambyte-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://exambyte-db:5432/exambyte_db
      SPRING_DATASOURCE_USERNAME: exambyte
      SPRING_DATASOURCE_PASSWORD: exambyte123
    ports:
      - "8080:8080"
    networks:
      - exambyte-network

networks:
  exambyte-network:
    driver: bridge

