config:
  roles: src/main/resources/roles.yaml

logging:
  level:
    org:
      springframework:
        security: info

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - read:public_repo

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: exambyte
    password: exambyte
  h2:
    console:
      enabled: true
      path: /h2-console
