config:
  roles: src/main/resources/roles.yaml

logging:
  level:
    org:
      springframework:
        security: info

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - read:public_repo

  datasource:
    url: jdbc:postgresql://localhost:5432/ExamByte
    driver-class-name: org.postgresql.Driver
    username: ExamByte
    password: ExamByte
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

